
services:
  redpanda:
    image: redpandadata/redpanda:v25.2.1
    container_name: redpanda
    command:
    - redpanda
    - start
    - --memory=1G
    - --reserve-memory=0M
    - --node-id=0
    - --check=false
    - --kafka-addr=PLAINTEXT://0.0.0.0:9092
    - --advertise-kafka-addr=redpanda:9092
    ports:
      - "9092:9092"
      - "29092:29092"

  redpanda-console:
    image: redpandadata/console:v2.8.8
    container_name: redpanda-console
    environment:
      - KAFKA_BROKERS=host.docker.internal:9092
    depends_on:
      - redpanda
    ports:
      - "8080:8080"

  clickhouse:
    image: clickhouse/clickhouse-server:25.7
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: ${CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    volumes:
      - /var/lib/clickhouse/
      - /var/log/clickhouse-server/

  superset:
    image: apache/superset:3.1.0
    container_name: superset
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      ADMIN_USERNAME: ${SUPERSET_USERNAME}
      ADMIN_PASSWORD: ${SUPERSET_PASSWORD}
      ADMIN_FIRST_NAME: ${SUPERSET_FIRST_NAME}
      ADMIN_LAST_NAME: ${SUPERSET_LAST_NAME}
    ports:
      - "8088:8088"
    depends_on:
      - clickhouse
    volumes:
      - ./superset_home:/app/superset_home